# Generated by Django 4.2.7 on 2023-12-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
