# Generated by Django 4.2.7 on 2023-12-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposclientes',
            fields=[
                ('id_tipcliente', models.TextField(db_column='ID_TipCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=255)),
            ],
            options={
                'db_table': 'TiposClientes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
