# Generated by Django 4.2.7 on 2023-12-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
