# Generated by Django 4.2.7 on 2023-11-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
